title = "Sample"

[owner]
name = "Example"
org = "Acme"

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
enabled = true

[[servers]]
name = "alpha"
ip = "10.0.0.1"

[[servers]]
name = "beta"
ip = "10.0.0.2"
